-- ---------------------------------------------------------------------
-- Wiki page shares — public read-only links generated by admins.
-- Run against the `testconx_wiki` database.
-- ---------------------------------------------------------------------

USE `testconx_wiki`;

CREATE TABLE IF NOT EXISTS `wiki_page_shares` (
    `ShareID`         INT UNSIGNED   NOT NULL AUTO_INCREMENT,
    `PageID`          INT UNSIGNED   NOT NULL,
    `Token`           CHAR(22)       NOT NULL,
    `IncludeChildren` TINYINT(1)     NOT NULL DEFAULT 0,
    `ExpiresAt`       DATETIME       NULL DEFAULT NULL,
    `RevokedAt`       DATETIME       NULL DEFAULT NULL,
    `CreatedBy`       INT UNSIGNED   NULL,
    `CreatedAt`       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ShareID`),
    UNIQUE KEY `uniq_wiki_page_shares_token` (`Token`),
    KEY `idx_wiki_page_shares_page` (`PageID`),
    KEY `idx_wiki_page_shares_active` (`RevokedAt`, `ExpiresAt`),
    CONSTRAINT `fk_wiki_page_shares_page`
        FOREIGN KEY (`PageID`) REFERENCES `wiki_pages`(`PageID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
